<?php 
$GLOBALS['conn'] = [
    "host" => "localhost",
    "banco" => "SiteManga",
    "usuario" => "root",
    "senha" => "",
];

$GLOBALS['sql'] = [
    "CREATE TABLE IF NOT EXISTS AUTORES (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        NOME VARCHAR(200) NOT NULL,
        BIOGRAFIA TEXT,
        DATA_NASCIMENTO DATE,
        NACIONALIDADE VARCHAR(100)
    );",

    "CREATE TABLE IF NOT EXISTS USUARIOS (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        NOME_DE_USUARIO VARCHAR(50) NOT NULL UNIQUE,
        EMAIL VARCHAR(100) NOT NULL UNIQUE,
        SENHA_HASH VARCHAR(255) NOT NULL,
        CRIADO_QUANDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );",

    "CREATE TABLE IF NOT EXISTS MANGAS (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        TITULO VARCHAR(200) NOT NULL,
        AUTOR_ID INT NOT NULL,
        DATA_PUBLICACAO DATE,
        SINOPSE TEXT,
        CRIADO_QUANDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        TIPO ENUM('MANGA', 'NOVEL') NOT NULL,
        STATUS VARCHAR(50),
        FOREIGN KEY (AUTOR_ID) REFERENCES AUTORES(ID) ON DELETE CASCADE
    );",

    "CREATE TABLE IF NOT EXISTS GENEROS (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        NOME VARCHAR(100) NOT NULL UNIQUE,
        DESCRICAO TEXT
    );",

    "CREATE TABLE IF NOT EXISTS GENEROS_MANGAS (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        MANGA_ID INT NOT NULL,
        GENERO_ID INT NOT NULL,
        FOREIGN KEY (MANGA_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
        FOREIGN KEY (GENERO_ID) REFERENCES GENEROS(ID) ON DELETE CASCADE
    );",

    "CREATE TABLE IF NOT EXISTS RANKINGS (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        MANGA_ID INT NOT NULL,
        TIPO_RANKING ENUM('POPULARIDADE', 'AVALIACAO', 'VENDAS') NOT NULL,
        POSICAO INT NOT NULL,
        DATA_RANKING DATE NOT NULL,
        FOREIGN KEY (MANGA_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE
    );",

    "CREATE TABLE IF NOT EXISTS AVALIACOES (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        MANGA_ID INT NOT NULL,
        USUARIO_ID INT NOT NULL,
        NOTA INT CHECK (NOTA >= 1 AND NOTA <= 10),
        COMENTARIO TEXT,
        DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (MANGA_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
    );",

    "CREATE TABLE IF NOT EXISTS FAVORITOS (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        MANGA_ID INT NOT NULL,
        USUARIO_ID INT NOT NULL,
        DATA_ADICIONADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (MANGA_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
    );",

    "CREATE TABLE IF NOT EXISTS COMENTARIOS_MANGA (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        MANGA_ID INT NOT NULL,
        USUARIO_ID INT NOT NULL,
        CONTEUDO TEXT NOT NULL,
        DATA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (MANGA_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
    );",

    "CREATE TABLE IF NOT EXISTS CAPITULOS (
        ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        MANGA_ID INT NOT NULL,
        NUMERO_CAPITULO VARCHAR(20) NOT NULL,
        TITULO_CAPITULO VARCHAR(200),
        DATA_LANCAMENTO DATE,
        SINOPSE TEXT,
        CRIADO_QUANDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (MANGA_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE
    );",
];

$GLOBALS['insert'] = [
    "INSERT INTO AUTORES (NOME, BIOGRAFIA, DATA_NASCIMENTO, NACIONALIDADE) VALUES
    ('Eiichiro Oda', 'Criador do famoso mangá One Piece.', '1975-01-01', 'Pintiarense'),
    ('Masashi Kishimoto', 'Autor do mangá Naruto.', '1974-11-08', 'Japonês'),
    ('Hajime Isayama', 'Conhecido por Attack on Titan.', '1986-08-29', 'Japonês'),
    ('Rumiko Takahashi', 'Famosa por Ranma ½ e Inuyasha.', '1957-10-10', 'Japonês'),
    ('Koyoharu Gotouge', 'Autor de Demon Slayer: Kimetsu no Yaiba.', '1989-05-05', 'Japonês'),
    ('Yoshihiro Togashi', 'Criador de Hunter x Hunter e Yu Yu Hakusho.', '1966-04-27', 'Japonês'),
    ('Tite Kubo', 'Autor do mangá Bleach.', '1977-06-26', 'Japonês'),
    ('Akira Toriyama', 'Famoso por Dragon Ball.', '1955-04-05', 'Japonês'),
    ('CLAMP', 'Grupo de mangakás conhecido por Cardcaptor Sakura e Holic.', 'Vários membros', 'Japonês'),
    ('Naoko Takeuchi', 'Criadora de Sailor Moon.', '1967-03-15', 'Japonês'),
    ('Kentaro Miura', 'Autor de Berserk.', '1966-07-11', 'Japonês'),
    ('Yana Toboso', 'Conhecida por Black Butler (Kuroshitsuji).', '1984-03-02', 'Japonês'),
    ('Kosuke Fujishima', 'Criador de Ah! My Goddess e Youre Under Arrest.', '1964-12-26', 'Japonês'),
    ('Sui Ishida', 'Autor de Tokyo Ghoul.', '1986-12-28', 'Japonês'),
    ('Takeshi Obata', 'Ilustrador de Death Note e Bakuman.', '1969-02-11', 'Japonês');",

    "INSERT INTO USUARIOS (NOME_DE_USUARIO, EMAIL, SENHA_HASH) VALUES
    ('mangafan123', 'megafan123@example.com', '$2y$10\$nAtqNT0xzjM.IheNjtWPpOqtXZVBZXpF1y.DV.efWqDr.DMq43zTO'),
    ('otakulover', 'otakulovers@example.com', '$2y$10$5MIPebCfnkvM8yxqmLBRFOsTAS.u2zrxfscdsG8L4xbnLVe66u4ui'),
    ('devmaster', 'devmaster@example.com', '$2y$10\$lPJNgJ549BrKcq0yEOjXv.8OoUmTNIEcHBWIzZS86ZvyKMSxzIiQO'),
    ('codewizard', 'codewizard@example.com', '$2y$10\$idRy3qs8h867Gltta9lIPuws.ags3F5Sx/wZJpmEyg4wecAD7gQWO'),
    ('pixelartist', 'pixelartist@example.com', '$2y$10\$v4QcIlSCGjSiZe089wVFYeuTLoWwMErO0N66gruErs6YkLYA8LFXS'),
    ('darkknight', 'darkknight@example.com', '$2y$10$.0wsArxFz8KmKs075hNBQucfmeNMDYy374Hmal.0QAYT5LFwIbmo.'),
    ('sunsetgirl', 'sunsetgirl@example.com', '$2y$10$40SJ.VlsffhSl6E11msTyO/cmP9miUEi6onzqM8OrAsT6yasY.J4O'),
    ('nightwolf', 'nightwolf@example.com', '$2y$10$8W3HvVxxkso5Ey9ULrIXmuG3WbTQ1dDTVSXu/FNOeNajlD.NEJe8S'),
    ('techgeek', 'techgeek@example.com', '$2y$10\$Pw7WmQxhHw4.h4r1OO.2aeiOeRlqxI0KDF0JV2piTB6Q2/K.prV2S'),
    ('gamersoul', 'gamersoul@example.com', '$2y$10\$xOFMhuFTc7YoLRpbeNSZ/OnwBdMHGdCahNbvKStGFlQFp3blddLe6'),
    ('retroplayer', 'retroplayer@example.com', '$2y$10\$uEb7mHe0ElaqYgIMBjHg3.bccDKw48BAgwVnMCHBnaXAkEv9OZlYm'),
    ('speedrunner', 'speedrunner@example.com', '$2y$10$9OGA6eoHTBRAiUA2l8384.7CfHu2eazbH.eEo.8EzsHeY22w0llpW'),
    ('cloudthinker', 'cloudthinker@example.com', '$2y$10\$qoOK1E4P6E8cvayGPRTSUeRiN9d5AS38NrLP.Gsk1hsUVx/Q4gc5e'),
    ('silentcoder', 'silentcoder@example.com', '$2y$10\$u0P8uha.PtfgssVHWjhafecSuTR8VFKuDr9I5nTx5Z2iWCoJKJhqW'),
    ('redphoenix', 'redphoenix@example.com', '$2y$10\$hkfI3JP/m4/.ixf1.CMBmeXoebR7RHVKihR83sibF/gllc3ZmWk1m'),
    ('bluehorizon', 'bluehorizon@example.com', '$2y$10\$yrYgeTtGoO1tVepRrhgYJeYb4.E3lSNB5ADzJEBfyO9psZmvSvm22'),
    ('ironmind', 'ironmind@example.com', '$2y$10\$WEk6FoWM3LucOnm2iJCf2e/Z168IjHCfx02vy2QcbtKv4MT2QXKNy'),
    ('lazycat', 'lazycat@example.com', '$2y$10\$svuoPl3wW2VUHaRsy8CKn.5oS7HU/HYiyQ7eki.KohXMVFYiP3Fdq'),
    ('stormbringer', 'stormbringer@example.com', '$2y$10\$HbMkYW90ZsF9qyt00eJXlO9aR3JKuKtoKRFojSdcML18NLFH/Rn0i'),
    ('voidwalker', 'voidwalker@example.com', '$2y$10\$z3.rN4prCgGZiL51t3xyD.JlesUdkBCRt28KWSLr2P3fDFGz5q31m'),
    ('dataminer', 'dataminer@example.com', '$2y$10\$V0v4S4KGMUTa9hAND72zMeTDX9Z/BZfwPHBNSuECs.opKVYRrjMoW'),
    ('bitcrusher', 'bitcrusher@example.com', '$2y$10\$sHL1PikWitAfcPiWraOj3OJv0j2A00O56RURaZ2Wm2KJH1DboWvmG'),
    ('logicloop', 'logicloop@example.com', '$2y$10\$zppqSbrZAgw4/L5BIp5UBOOzrNVG8SgK6IiIqHNqoXALFGT9vELDq'),
    ('stacktrace', 'stacktrace@example.com', '$2y$10\$fLoQGtREa0GSFTv.MsA6QeoM2KsphgkSfVeHdP1TWG/kA6ovMN/ey'),
    ('bytehunter', 'bytehunter@example.com', '$2y$10\$u/4UtKDWyW85fqYDsWMa/.8Gc6gtltKRufB.oE.ktDBRQXWOKtcFu'),
    ('kernelpanic', 'kernelpanic@example.com', '$2y$10\$koudmXIEfesUY9qqrNZ.EOkb5LDykt3CBO6tOI1O/xHEJ4PCD/eJS'),
    ('scriptkid', 'scriptkid@example.com', '$2y$10\$pZORijUW9U36jjqHqVclEeWcB9JW9eSMO4xOywpxfoctO0PmZCQaG'),
    ('phantomuser', 'phantomuser@example.com', '$2y$10$6IjejYShJtl9.wyHKJf5Xu5jCEty5Od7ogRtrBfAAxqs6g4ZE4qUO'),
    ('neonshadow', 'neonshadow@example.com', '$2y$10$8.R2IbJK2yWhaUzISGysGO654f5A6apewImA3zlR1QwHGw30jrzgm'),
    ('frostbyte', 'frostbyte@example.com', '$2y$10$89kgHnQLgyCVdsKSIvrg1e1b1z6svUlL1lNKqCv1M1eWBJhZk/B1u');",

    "INSERT INTO MANGAS (TITULO, AUTOR_ID, DATA_PUBLICACAO, SINOPSE, TIPO, STATUS) VALUES
    ('One Piece', '1', '1997-07-22', 'A aventura de Monkey D. Luffy em busca do tesouro One Piece.', 'MANGA', 'Em andamento'),
    ('Naruto', '2', '1999-09-21', 'A jornada de Naruto Uzumaki para se tornar Hokage.', 'MANGA', 'Concluído'),
    ('Attack on Titan', '3', '2009-09-09', 'A luta da humanidade contra os Titãs.', 'MANGA', 'Concluído'),
    ('Demon Slayer: Kimetsu no Yaiba', '5', '2016-02-15', 'Tanjiro Kamado luta contra demônios para salvar sua irmã.', 'MANGA', 'Concluído'),
    ('Bleach', '7', '2001-08-07', 'Ichigo Kurosaki torna-se um Ceifador de Almas.', 'MANGA', 'Concluído'),
    ('Dragon Ball', '8', '1984-12-03', 'As aventuras de Goku em busca das Esferas do Dragão.', 'MANGA', 'Concluído'),
    ('Tokyo Ghoul', '14', '2011-09-08', 'Kaneki Ken se transforma em meio humano e meio ghoul.', 'MANGA', 'Concluído'),
    ('Death Note', '15', '2003-12-01', 'Light Yagami encontra um caderno que pode matar pessoas.', 'MANGA', 'Concluído'),
    ('Berserk', '11', '1989-08-25', 'A jornada sombria de Guts em um mundo medieval cheio de demônios.', 'MANGA', 'Em andamento'),
    ('Sailor Moon', '10', '1991-03-28', 'As aventuras de Usagi Tsukino como Sailor Moon.', 'MANGA', 'Concluído'),
    ('Hunter x Hunter', '6', '1998-03-03', 'Gon Freecss busca se tornar um Hunter e encontrar seu pai.', 'MANGA', 'Em andamento'),
    ('Black Butler (Kuroshitsuji)', '12', '2006-10-16', 'Ciel Phantomhive faz um pacto com um demônio para vingar sua família.', 'MANGA', 'Em andamento'),
    ('Ah! My Goddess', '13', '1988-09-07', 'A vida de Keiichi Morisato muda ao conhecer uma deusa.', 'MANGA', 'Em andamento'),
    ('Cardcaptor Sakura', '9', '1996-05-01', 'Sakura Kinomoto descobre seus poderes mágicos ao capturar cartas mágicas.', 'MANGA', 'Concluído'),
    ('Ranma ½', '4', '1987-08-07', 'As aventuras cômicas de Ranma Saotome, que se transforma em garota ao ser molhado com água fria.', 'MANGA', 'Concluído');",

    "INSERT INTO GENEROS (NOME, DESCRICAO) VALUES
    ('Ação', 'Gênero focado em cenas de ação e aventura.'),
    ('Comédia', 'Gênero que visa provocar risadas e entretenimento leve.'),
    ('Drama', 'Gênero que explora emoções profundas e conflitos pessoais.'),
    ('Fantasia', 'Gênero que envolve elementos mágicos ou sobrenaturais.'),
    ('Romance', 'Gênero centrado em histórias de amor e relacionamentos.'),
    ('Terror', 'Gênero destinado a assustar e criar suspense.'),
    ('Ficção Científica', 'Gênero que explora conceitos científicos e tecnológicos futuristas.'),
    ('Mistério', 'Gênero que envolve enigmas e investigações.'),
    ('Slice of Life', 'Gênero que retrata a vida cotidiana de forma realista.'),
    ('Esporte', 'Gênero focado em atividades esportivas e competições.'),
    ('Histórico', 'Gênero que se passa em períodos históricos específicos.'),
    ('Sobrenatural', 'Gênero que envolve fenômenos além da explicação científica.'),
    ('Mecha', 'Gênero que apresenta robôs gigantes e tecnologia avançada.'),
    ('Horror', 'Gênero que busca evocar medo e tensão psicológica.'),
    ('Aventura', 'Gênero que envolve jornadas e explorações emocionantes.');",

    "INSERT INTO GENEROS_MANGAS (MANGA_ID, GENERO_ID) VALUES
    (1, 1),
    (1, 10),
    (2, 1),
    (2, 5),
    (3, 1),
    (3, 12),
    (4, 1),
    (4, 12),
    (5, 1),
    (5, 12),
    (6, 1),
    (6, 10),
    (7, 12),
    (7, 14),
    (8, 12),
    (8, 4),
    (9, 14),
    (9, 3),
    (10, 5),
    (10, 4),
    (11, 1),
    (11, 10),
    (12, 12),
    (12, 4),
    (13, 5),
    (13, 4),
    (14, 4),
    (14, 2),
    (15, 2),
    (15, 12);",

    "INSERT INTO RANKINGS (MANGA_ID, TIPO_RANKING, POSICAO, DATA_RANKING) VALUES
    (1, 'POPULARIDADE', 1, '2024-01-01'),
    (2, 'POPULARIDADE', 2, '2024-01-01'),
    (3, 'POPULARIDADE', 3, '2024-01-01'),
    (4, 'POPULARIDADE', 4, '2024-01-01'),
    (5, 'POPULARIDADE', 5, '2024-01-01'),
    (6, 'POPULARIDADE', 6, '2024-01-01'),
    (7, 'POPULARIDADE', 7, '2024-01-01'),
    (8, 'POPULARIDADE', 8, '2024-01-01'),
    (9, 'POPULARIDADE', 9, '2024-01-01'),
    (10, 'POPULARIDADE', 10, '2024-01-01'),
    (1, 'AVALIACAO', 1, '2024-01-01'),
    (2, 'AVALIACAO', 2, '2024-01-01'),
    (3, 'AVALIACAO', 3, '2024-01-01'),
    (4, 'AVALIACAO', 4, '2024-01-01'),
    (5, 'AVALIACAO', 5, '2024-01-01'),
    (6, 'AVALIACAO', 6, '2024-01-01'),
    (7, 'AVALIACAO', 7, '2024-01-01'),
    (8, 'AVALIACAO', 8, '2024-01-01'),
    (9, 'AVALIACAO', 9, '2024-01-01'),
    (10, 'AVALIACAO', 10, '2024-01-01'),
    (1, 'VENDAS', 1, '2024-01-01'),
    (2, 'VENDAS', 2, '2024-01-01'),
    (3, 'VENDAS', 3, '2024-01-01'),
    (4, 'VENDAS', 4, '2024-01-01'),
    (5, 'VENDAS', 5, '2024-01-01'),
    (6, 'VENDAS', 6, '2024-01-01'),
    (7, 'VENDAS', 7, '2024-01-01'),
    (8, 'VENDAS', 8, '2024-01-01'),
    (9, 'VENDAS', 9, '2024-01-01'),
    (10, 'VENDAS', 10, '2024-01-01');",

    "INSERT INTO AVALIACOES (MANGA_ID, USUARIO_ID, NOTA, COMENTARIO) VALUES
    (1, 1, 9, 'Incrível história e personagens cativantes!'),
    (2, 2, 8, 'Adorei a arte e o enredo.'),
    (3, 3, 10, 'Um dos melhores mangás que já li!'),
    (4, 4, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
    (5, 5, 9, 'Personagens profundos e trama envolvente.'),
    (6, 1, 8, 'Gostei muito dos temas abordados.'),
    (7, 2, 10, 'Simplesmente fantástico!'),
    (8, 3, 7, 'Interessante, mas com alguns clichês.'),
    (9, 4, 9, 'Ação e aventura na medida certa.'),
    (10, 5, 8, 'Recomendo para fãs do gênero.'),
    (11, 1, 10, 'Arte impressionante e história emocionante.'),
    (12, 2, 9, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
    (13, 3, 8, 'Leitura agradável e fluida.'),
    (14, 4, 10, 'Um clássico que todo fã deve ler.'),
    (15, 5, 9, 'Trama envolvente e personagens memoráveis.'),
    (1, 1, 9, 'Continuação à altura do primeiro volume!'),
    (2, 2, 8, 'Gostei, mas esperava mais reviravoltas.'),
    (3, 3, 10, 'Incrível desenvolvimento dos personagens!'),
    (4, 4, 7, 'Boa leitura, mas faltou algo a mais.'),
    (5, 5, 9, 'Ação constante e bem escrita.'),
    (6, 1, 8, 'Adorei os novos personagens introduzidos.'),
    (7, 2, 10, 'Simplesmente espetacular!'),
    (8, 3, 7, 'Algumas partes foram um pouco lentas.'),
    (9, 4, 9, 'Muito emocionante e cheio de surpresas.'),
    (10, 5, 8, 'Recomendo para quem gosta de ação.'),
    (11, 1, 10, 'Arte ainda melhor que o primeiro volume!'),
    (12, 2, 9, 'História envolvente e bem construída.'),
    (13, 3, 8, 'Leitura agradável e divertida.'),
    (14, 4, 10, 'Um must-read para qualquer fã de mangás.'),
    (15, 5, 9, 'Trama sólida e personagens cativantes.'),
    (1, 1, 9, 'Terceiro volume à altura dos anteriores!'),
    (2, 2, 8, 'Gostei, mas esperava mais ação.'),
    (3, 3, 10, 'Desenvolvimento incrível dos personagens!'),
    (4, 4, 7, 'Boa leitura, mas faltou algo especial.'),
    (5, 5, 9, 'Ação constante e bem escrita.'),
    (6, 1, 8, 'Novos personagens interessantes.'),
    (7, 2, 10, 'Simplesmente espetacular!'),
    (8, 3, 7, 'Algumas partes foram um pouco lentas.'),
    (9, 4, 9, 'Muito emocionante e cheio de surpresas.'),
    (10, 5, 8, 'Recomendo para quem gosta de ação.'),
    (11, 1, 10, 'Arte ainda melhor que os volumes anteriores!'),
    (12, 2, 9, 'História envolvente e bem construída.'),
    (13, 3, 8, 'Leitura agradável e divertida.'),
    (14, 4, 10, 'Um must-read para qualquer fã de mangás.'),
    (15, 5, 9, 'Trama sólida e personagens cativantes.');",

    "INSERT INTO FAVORITOS (MANGA_ID, USUARIO_ID) VALUES
    (1, 1),
    (2, 1),
    (3, 2),
    (4, 2),
    (5, 3),
    (6, 3),
    (7, 4),
    (8, 4),
    (9, 5),
    (10, 5),
    (11, 1),
    (12, 2),
    (13, 3),
    (14, 4),
    (15, 5),
    (1, 2),
    (2, 3),
    (3, 4),
    (4, 5),
    (5, 1),
    (6, 2),
    (7, 3),
    (8, 4),
    (9,21),
    (8,20),
    (7,19),
    (6,18),
    (5,17),
    (4,16),
    (3,15),
    (2,14),
    (1,13),
    (10,12),
    (11,11),
    (12,10),
    (13,9),
    (14,8),
    (15,7),
    (1,6);",

    "INSERT INTO COMENTARIOS_MANGA (MANGA_ID, USUARIO_ID, CONTEUDO) VALUES
    (1, 1, 'Esse mangá é incrível! A história me prendeu desde o primeiro capítulo.'),
    (2, 2, 'Adorei os personagens e a arte é fantástica.'),
    (3, 3, 'Um dos melhores mangás que já li na vida!'),
    (4, 4, 'A trama é envolvente e cheia de reviravoltas.'),
    (5, 5, 'Recomendo para todos os fãs de mangás de ação.'),
    (1, 2, 'O desenvolvimento dos personagens é excelente.'),
    (2, 3, 'A história é cativante e cheia de emoção.'),
    (3, 4, 'Não consegui parar de ler até terminar!'),
    (4, 5, 'A arte é detalhada e muito bem feita.'),
    (5, 1, 'Mal posso esperar pelo próximo volume!'),
    (6, 2, 'A narrativa é fluida e fácil de acompanhar.'),
    (7, 3, 'Os diálogos são muito bem escritos.'),
    (8, 4, 'A ambientação do mangá é incrível.'),
    (9, 5, 'Cada capítulo é melhor que o anterior.'),
    (10, 1, 'Os vilões são muito bem construídos.'),
    (11, 2, 'A ação é constante e emocionante.'),
    (12, 3, 'Os personagens secundários também são interessantes.'),
    (13, 4, 'A história tem um ritmo perfeito.'),
    (14, 5, 'A arte evolui muito ao longo do mangá.'),
    (15, 1, 'Um mangá que todo fã deve ler pelo menos uma vez.'),
    (6, 3, 'A trama é cheia de surpresas e reviravoltas.'),
    (7, 4, 'Os personagens têm profundidade e complexidade.'),
    (8, 5, 'A história é emocionante e tocante.'),
    (9, 1, 'A arte é simplesmente deslumbrante.'),
    (10, 2, 'Cada capítulo me deixou ansioso pelo próximo.'),
    (11, 3, 'Os temas abordados são muito relevantes.'),
    (12, 4, 'A narrativa é envolvente e cativante.'),
    (13, 5, 'Os personagens são memoráveis e únicos.'),
    (14, 1, 'A história é cheia de ação e aventura.'),
    (15, 2, 'Um mangá que eu recomendo para todos os meus amigos.'),
    (1, 3, 'A trama é complexa e muito bem desenvolvida.'),
    (2, 4, 'Os personagens têm uma química incrível.'),
    (3, 5, 'A arte é detalhada e cheia de vida.'),
    (4, 1, 'Cada capítulo é uma nova surpresa.'),
    (5, 2, 'A história é emocionante e cheia de reviravoltas.'),
    (6, 4, 'Os personagens são profundos e bem construídos.'),
    (7, 5, 'A narrativa é fluida e fácil de seguir.'),
    (8, 1, 'A ambientação do mangá é fantástica.'),
    (9, 2, 'Cada capítulo me deixou querendo mais.'),
    (10, 3, 'Os vilões são complexos e interessantes.'),
    (11, 4, 'A ação é constante e emocionante.'),
    (12, 5, 'Os personagens secundários são tão interessantes quanto os principais.'),
    (13, 1, 'A história tem um ritmo perfeito e envolvente.'),
    (14, 2, 'A arte evolui muito ao longo do mangá.'),
    (15, 3, 'Um mangá que todo fã deve ler pelo menos uma vez na vida.');",

    "INSERT INTO CAPITULOS (MANGA_ID, NUMERO_CAPITULO, TITULO_CAPITULO, DATA_LANCAMENTO, SINOPSE) VALUES
    (1, 1, 'O Início da Aventura', '1997-07-22', 'Monkey D. Luffy começa sua jornada para se tornar o Rei dos Piratas.'),
    (2, 1, 'O Nascimento de um Ninja', '1999-09-21', 'Naruto Uzumaki é apresentado como um jovem ninja com grandes sonhos.'),
    (3, 1, 'O Ataque dos Titãs', '2009-09-09', 'A humanidade enfrenta a ameaça dos Titãs pela primeira vez.'),
    (4, 1, 'A Espada do Caçador de Demônios', '2016-02-15', 'Tanjiro Kamado inicia sua luta contra os demônios para salvar sua irmã.'),
    (5, 1, 'O Ceifador de Almas', '2001-08-07', 'Ichigo Kurosaki descobre seus poderes como Ceifador de Almas.'),
    (6, 1, 'O Começo da Jornada', '1998-03-03', 'Gon Freecss decide se tornar um Hunter para encontrar seu pai.'),
    (7, 1, 'O Primeiro Encontro com um Ghoul', '2011-09-08', 'Kaneki Ken enfrenta sua transformação em meio humano e meio ghoul.'),
    (8, 1, 'O Caderno da Morte', '2003-12-01', 'Light Yagami encontra o Death Note e começa sua missão de justiça.'),
    (9, 1, 'A Espada do Berserk', '1989-08-25', 'Guts inicia sua jornada sombria em um mundo cheio de demônios.'),
    (10, 1, 'A Guerreira da Lua', '1991-03-28', 'Usagi Tsukino descobre seus poderes como Sailor Moon.'),
    (11, 1, 'O Teste do Hunter', '1998-03-03', 'Gon Freecss participa do exame para se tornar um Hunter.'),
    (12, 1, 'O Pacto com o Demônio', '2006-10-16', 'Ciel Phantomhive faz um pacto com Sebastian Michaelis.'),
    (13, 1, 'O Encontro com a Deusa', '1988-09-07', 'Keiichi Morisato conhece a deusa Belldandy.'),
    (14, 1, 'A Captura da Primeira Carta', '1996-05-01', 'Sakura Kinomoto começa sua missão de capturar as cartas mágicas.'),
    (15, 1, 'O Treinamento de Ranma', '1987-08-07', 'Ranma Saotome inicia seu treinamento nas artes marciais.'),
    (1, 2, 'O Pirata Almirante', '1997-08-05', 'Luffy encontra o pirata Almirante pela primeira vez.'),
    (2, 2, 'A Promessa de Naruto', '1999-10-05', 'Naruto faz uma promessa importante para seus amigos.'),
    (3, 2, 'A Muralha se Abre', '2009-09-23', 'Os Titãs rompem a muralha e invadem a cidade.'),
    (4, 2, 'O Treinamento de Tanjiro', '2016-03-01', 'Tanjiro começa seu treinamento para se tornar um caçador de demônios.'),
    (5, 2, 'A Batalha na Cidade', '2001-08-21', 'Ichigo enfrenta um poderoso inimigo na cidade.'),
    (6, 2, 'O Encontro com Killua', '1998-03-17', 'Gon conhece Killua Zoldyck, que se torna seu amigo.'),
    (7, 2, 'A Luta pela Sobrevivência', '2011-09-22', 'Kaneki luta para sobreviver em um mundo perigoso.'),
    (8, 2, 'O Primeiro Alvo', '2004-01-15', 'Light escolhe sua primeira vítima com o Death Note.'),
    (9, 2, 'A Marca do Destino', '1989-09-08', 'Guts recebe uma marca que o persegue constantemente.'),
    (10, 2, 'A Batalha das Sailors', '1991-04-11', 'Sailor Moon enfrenta suas primeiras inimigas.'),
    (11, 2, 'O Desafio de Leorio', '1998-03-31', 'Leorio Paradinight enfrenta um desafio difícil no exame Hunter.'),
    (12, 2, 'O Segredo de Sebastian', '2006-11-01', 'Ciel começa a desvendar os segredos de seu mordomo demoníaco.'),
    (13, 2, 'A Vida com Belldandy', '1988-09-21', 'Keiichi se adapta à vida com a deusa Belldandy.'),
    (14, 2, 'A Captura da Segunda Carta', '1996-05-15', 'Sakura captura sua segunda carta mágica.'),
    (15, 2, 'O Encontro com Akane', '1987-08-21', 'Ranma conhece Akane Tendo, que se torna sua noiva relutante.'),
    (1, 3, 'A Luta contra Buggy', '1997-08-19', 'Luffy enfrenta o pirata Buggy em uma batalha épica.'),
    (2, 3, 'O Desafio de Sasuke', '1999-10-19', 'Naruto enfrenta Sasuke Uchiha em um duelo intenso.'),
    (3, 3, 'A Defesa da Muralha', '2009-10-07', 'Os sobreviventes tentam defender a muralha dos Titãs.'),
    (4, 3, 'A Espada Nichirin', '2016-03-15', 'Tanjiro recebe sua espada especial para caçar demônios.'),
    (5, 3, 'A Batalha no Hospital', '2001-09-04', 'Ichigo luta contra inimigos dentro de um hospital.'),
    (6, 3, 'O Encontro com Kurapika', '1998-04-14', 'Gon conhece Kurapika, que busca vingança contra os Homens de Preto.'),
    (7, 3, 'A Fuga de Kaneki', '2011-10-06', 'Kaneki tenta escapar dos ghouls que o perseguem.'),
    (8, 3, 'A Conspiração dos Shinigamis', '2004-01-29', 'Light descobre uma conspiração entre os shinigamis.'),
    (9, 3, 'O Encontro com Griffith', '1989-09-22', 'Guts conhece Griffith, líder do Bando do Falcão.'),
    (10, 3, 'A Batalha contra Queen Beryl', '1991-04-25', 'Sailor Moon enfrenta a vilã Queen Beryl.'),
    (11, 3, 'O Desafio de Kurapika', '1998-04-28', 'Kurapika enfrenta um desafio perigoso no exame Hunter.'),
    (12, 3, 'O Passado de Ciel', '2006-11-15', 'Ciel começa a revelar seu passado sombrio.'),
    (13, 3, 'A Deusa da Fortuna', '1988-10-05', 'Belldandy traz sorte para a vida de Keiichi.'),
    (14, 3, 'A Captura da Terceira Carta', '1996-05-29', 'Sakura captura sua terceira carta mágica.'),
    (15, 3, 'O Treinamento de Akane', '1987-09-04', 'Akane começa seu treinamento em artes marciais.'),
    (1, 4, 'A Batalha no Baratie', '1997-09-02', 'Luffy enfrenta Don Krieg no restaurante flutuante Baratie.'),
    (2, 4, 'A Promessa de Sakura', '1999-11-02', 'Naruto faz uma promessa importante para Sakura Haruno.'),
    (3, 4, 'A Retomada da Muralha', '2009-10-21', 'Os humanos planejam retomar a muralha dos Titãs.'),
    (4, 4, 'O Encontro com Nezuko', '2016-03-29', 'Tanjiro encontra sua irmã Nezuko, que foi transformada em demônio.'),
    (5, 4, 'A Batalha na Soul Society', '2001-09-18', 'Ichigo invade a Soul Society para resgatar Rukia.'),
    (6, 4, 'O Encontro com Leorio', '1998-04-28', 'Gon conhece Leorio Paradinight, que sonha em ser médico.'),
    (7, 4, 'A Luta contra Touka', '2011-10-20', 'Kaneki enfrenta Touka Kirishima em um confronto intenso.'),
    (8, 4, 'A Ascensão de Kira', '2004-02-12', 'Light começa a ser conhecido como Kira.'),
    (9, 4, 'A Queda do Bando do Falcão', '1989-10-06', 'O Bando do Falcão enfrenta uma grande derrota.'),
    (10, 4, 'A Batalha contra os Shitennou', '1991-05-09', 'Sailor Moon enfrenta os generais Shitennou.'),
    (11, 4, 'O Desafio de Gon', '1998-05-12', 'Gon enfrenta um desafio difícil no exame Hunter.'),
    (12, 4, 'O Contrato com o Demônio', '2006-11-29', 'Ciel reforça seu contrato com Sebastian.'),
    (13, 4, 'A Vida na Terra dos Deuses', '1988-10-19', 'Keiichi explora a vida com as deusas na Terra.'),
    (14, 4, 'A Captura da Quarta Carta', '1996-06-12', 'Sakura captura sua quarta carta mágica.'),
    (15, 4, 'O Encontro com Shampoo', '1987-09-18', 'Ranma conhece Shampoo, uma guerreira chinesa.'),
    (1, 5, 'A Luta contra Arlong', '1997-09-16', 'Luffy enfrenta o pirata Arlong para libertar Nami.'),
    (2, 5, 'A Promessa de Sasuke', '1999-11-16', 'Naruto faz uma promessa importante para Sasuke Uchiha.'),
    (3, 5, 'A Batalha Final pela Muralha', '2009-11-04', 'Os humanos enfrentam os Titãs na batalha final pela muralha.'),
    (4, 5, 'O Treinamento com Urokodaki', '2016-04-12', 'Tanjiro treina com o mestre Urokodaki para se tornar um caçador de demônios.'),
    (5, 5, 'A Batalha contra Byakuya', '2001-10-02', 'Ichigo enfrenta Byakuya Kuchiki em uma batalha épica.'),
    (6, 5, 'O Encontro com Hisoka', '1998-05-26', 'Gon conhece Hisoka, um misterioso e poderoso Hunter.'),
    (7, 5, 'A Fuga de Anteiku', '2011-11-03', 'Kaneki tenta escapar do café Anteiku com seus amigos ghouls.'),
    (8, 5, 'A Caçada a Kira', '2004-02-26', 'Light enfrenta a investigação liderada por L para capturá-lo.'),
    (9, 5, 'A Ascensão de Griffith', '1989-10-20', 'Griffith começa a ascender ao poder dentro do Bando do Falcão.'),
    (10, 5, 'A Batalha contra Nephrite', '1991-05-23', 'Sailor Moon enfrenta o general Nephrite.'),
    (11, 5, 'O Desafio de Killua', '1998-06-09', 'Killua Zoldyck enfrenta um desafio perigoso no exame Hunter.'),
    (12, 5, 'O Passado de Sebastian', '2006-12-13', 'Sebastian revela mais sobre seu passado demoníaco.'),
    (13, 5, 'A Deusa do Amor', '1988-11-02', 'Belldandy ajuda Keiichi em assuntos do coração.'),
    (14, 5, 'A Captura da Quinta Carta', '1996-06-26', 'Sakura captura sua quinta carta mágica.'),
    (15, 5, 'O Treinamento de Shampoo', '1987-10-02', 'Shampoo começa seu treinamento em artes marciais.'),
    (1, 6, 'A Batalha em Alabasta', '1997-10-07', 'Luffy enfrenta Crocodile para salvar o reino de Alabasta.'),
    (2, 6, 'A Promessa de Hinata', '1999-12-07', 'Naruto faz uma promessa importante para Hinata Hyuga.'),
    (3, 6, 'A Libertação da Muralha', '2009-11-18', 'Os humanos conseguem libertar a muralha dos Titãs.'),
    (4, 6, 'O Encontro com Zenitsu', '2016-04-26', 'Tanjiro conhece Zenitsu Agatsuma, um companheiro caçador de demônios.'),
    (5, 6, 'A Batalha contra Renji', '2001-10-16', 'Ichigo enfrenta Renji Abarai em uma luta intensa.'),
    (6, 6, 'O Encontro com Gon', '1998-06-23', 'Killua conhece Gon Freecss, que se torna seu melhor amigo.'),
    (7, 6, 'A Luta contra Rize', '2011-11-17', 'Kaneki enfrenta Rize Kamishiro em um confronto decisivo.'),
    (8, 6, 'A Guerra dos Shinigamis', '2004-03-11', 'Light enfrenta uma guerra total entre os shinigamis.'),
    (9, 6, 'A Queda de Griffith', '1989-11-03', 'Griffith enfrenta uma grande queda em sua jornada.'),
    (10, 6, 'A Batalha contra Zoisite', '1991-06-06', 'Sailor Moon enfrenta o general Zoisite.'),
    (11, 6, 'O Desafio de Hisoka', '1998-07-07', 'Hisoka enfrenta um desafio perigoso no exame Hunter.'),
    (12, 6, 'O Contrato com Ciel', '2006-12-27', 'Ciel reforça seu contrato com Sebastian para novos desafios.'),
    (13, 6, 'A Vida no Mundo dos Deuses', '1988-11-16', 'Keiichi explora mais sobre a vida com as deusas na Terra.'),
    (14, 6, 'A Captura da Sexta Carta', '1996-07-10', 'Sakura captura sua sexta carta mágica.'),
    (15, 6, 'O Encontro com Ryoga', '1987-10-16', 'Ranma conhece Ryoga Hibiki, um rival em artes marciais.'),
    (1, 7 , 'A Luta contra Enel', '1997-10-21', 'Luffy enfrenta o deus Enel para salvar a Ilha Skypiea.'),
    (2, 7, 'A Promessa de Shikamaru', '2000-01-04', 'Naruto faz uma promessa importante para Shikamaru Nara.'),
    (3, 7, 'A Reconstrução da Muralha', '2009-12-02', 'Os humanos começam a reconstruir a muralha após a guerra.'),
    (4, 7, 'O Treinamento com Sakonji', '2016-05-10', 'Tanjiro treina com o mestre Sakonji Urokodaki para aprimorar suas habilidades.'),
    (5, 7, 'A Batalha contra Uryu', '2001-10-30', 'Ichigo enfrenta Uryu Ishida em uma luta tensa.'),
    (6, 7, 'O Encontro com Leol', '1998-07-21', 'Killua conhece Leol, um membro dos Homens de Preto.'),
    (7, 7, 'A Fuga de Cochlea', '2011-12-01', 'Kaneki tenta escapar da prisão de Cochlea com seus aliados ghouls.'),
    (8, 7, 'A Revelação de L', '2004-03-25', 'Light descobre a verdadeira identidade de L.'),
    (9, 7, 'A Ascensão do Reino de Falconia', '1989-11-17', 'Griffith estabelece o Reino de Falconia como um poder dominante.'),
    (10, 7, 'A Batalha contra Kunzite', '1991-06-20', 'Sailor Moon enfrenta o general Kunzite.'),
    (11, 7, 'O Desafio de Gon e Killua', '1998-08-04', 'Gon e Killua enfrentam um desafio perigoso juntos no exame Hunter.'),
    (12, 7, 'O Passado de Ciel e Sebastian', '2007-01-10', 'Ciel e Sebastian revelam mais sobre seus passados sombrios.'),
    (13, 7, 'A Deusa da Sabedoria', '1988-11-30', 'Belldandy ajuda Keiichi com conselhos sábios.'),
    (14, 7, 'A Captura da Sexta Carta', '1996-07-10', 'Sakura captura sua sexta carta mágica.'),
    (15, 7, 'O Treinamento de Ranma e Akane', '1987-10-16', 'Ranma e Akane treinam juntos para melhorar suas habilidades.'),
    (1, 8, 'A Batalha contra Crocodile', '1997-11-04', 'Luffy derrota Crocodile e salva Alabasta.'),
    (2, 8, 'A Promessa de Rock Lee', '2000-01-18', 'Naruto faz uma promessa importante para Rock Lee.'),
    (3, 8, 'A Paz na Muralha', '2009-12-16', 'A muralha é restaurada e a paz retorna à humanidade.'),
    (4, 8, 'O Encontro com Inosuke', '2016-05-24', 'Tanjiro conhece Inosuke Hashibira, um caçador de demônios selvagem.'),
    (5, 8, 'A Batalha contra Chad', '2001-11-13', 'Ichigo enfrenta Chad Yasutora em uma luta intensa.'),
    (6, 8, 'O Encontro com Bonolenov', '1998-08-18', 'Killua conhece Bonolenov Ndongo, um membro dos Homens de Preto.'),
    (7, 8, 'A Luta contra Yamori', '2011-12-15', 'Kaneki enfrenta Yamori em uma batalha brutal.'),
    (8, 8, 'A Queda de L', '2004-04-08', 'L enfrenta sua queda final contra Light.'),
    (9, 8, 'A Consolidação do Reino de Falconia', '1989-12-01', 'Griffith consolida seu poder no Reino de Falconia.'),
    (10, 8, 'A Batalha contra Zoisite e Kunzite', '1991-07-04', 'Sailor Moon enfrenta os generais Zoisite e Kunzite juntos.'),
    (11, 8, 'O Desafio Final do Exame Hunter', '1998-08-18', 'Gon e Killua enfrentam o desafio final do exame Hunter.'),
    (12, 8, 'O Futuro de Ciel e Sebastian', '2007-01-24', 'Ciel e Sebastian discutem seus planos futuros.'),
    (13, 8, 'A Vida com as Deusas na Terra', '1988-12-14', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 8, 'A Captura da Sétima Carta', '1996-07-24', 'Sakura captura sua sétima carta mágica.'),
    (15, 8, 'O Treinamento Avançado de Ranma e Akane', '1987-10-30', 'Ranma e Akane avançam em seu treinamento conjunto.'),
    (1, 9, 'A Luta contra Lucci', '1997-11-18', 'Luffy enfrenta Rob Lucci para salvar Robin.'),
    (2, 9, 'A Promessa de Gaara', '2000-02-01', 'Naruto faz uma promessa importante para Gaara.'),
    (3, 9, 'A Celebração na Muralha', '2010-01-06', 'A humanidade celebra a paz restaurada na muralha.'),
    (4, 9, 'O Treinamento com Sakonji Urokodaki', '2016-06-07', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
    (5, 9, 'A Batalha contra Ishida', '2001-11-27', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
    (6, 9, 'O Encontro com Shalnark', '1998-09-01', 'Killua conhece Shalnark, um membro dos Homens de Preto.'),
    (7, 9, 'A Fuga de Anteiku Parte 2', '2011-12-29', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
    (8, 9, 'A Conclusão da Guerra dos Shinigamis', '2004-04-22', 'Light enfrenta a conclusão da guerra entre os shinigamis.'),
    (9, 9, 'A Expansão do Reino de Falconia', '1989-12-15', 'Griffith expande seu poder no Reino de Falconia.'),
    (10, 9, 'A Batalha contra Nephrite e Zoisite', '1991-07-18', 'Sailor Moon enfrenta os generais Nephrite e Zoisite juntos.'),
    (11, 9, 'O Desafio Final de Gon e Killua', '1998-09-15', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter.'),
    (12, 9, 'O Futuro Incerto de Ciel e Sebastian', '2007-02-07', 'Ciel e Sebastian discutem seu futuro incerto.'),
    (13, 9, 'A Vida com as Deusas na Terra Parte 2', '1988-12-28', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 9, 'A Captura da Oitava Carta', '1996-08-07', 'Sakura captura sua oitava carta mágica.'),
    (15, 9, 'O Treinamento Final de Ranma e Akane', '1987-11-13', 'Ranma e Akane concluem seu treinamento conjunto.'),
    (1, 10, 'A Batalha contra Kaku', '1997-12-02', 'Luffy enfrenta Kaku na luta para salvar seus amigos.'),
    (2, 10, 'A Promessa de Temari', '2000-02-15', 'Naruto faz uma promessa importante para Temari.'),
    (3, 10, 'A Renovação da Muralha', '2010-01-20', 'A muralha é renovada e a paz é mantida na humanidade.'),
    (4, 10, 'O Encontro com Giyu Tomioka', '2016-06-21', 'Tanjiro conhece Giyu Tomioka, um caçador de demônios de elite.'),
    (5, 10, 'A Batalha contra Orihime', '2001-12-11', 'Ichigo enfrenta Orihime Inoue em uma luta emocional.'),
    (6, 10, 'O Encontro com Franklin', '1998-09-15', 'Killua conhece Franklin Bordeau, um membro dos Homens de Preto.'),
    (7, 10, 'A Luta contra Jason', '2012-01-12', 'Kaneki enfrenta Jason em uma batalha decisiva.'),
    (8, 10, 'O Desfecho da Queda de L', '2004-05-06', 'L enfrenta seu desfecho final contra Light.'),
    (9, 10, 'A Estabilização do Reino de Falconia', '1989-12-29', 'Griffith estabiliza seu poder no Reino de Falconia.'),
    (10, 10, 'A Batalha contra os Shitennou Parte 2', '1991-08-01', 'Sailor Moon enfrenta os generais Shitennou novamente.'),
    (11, 10, 'O Desafio Final de Gon e Killua Parte 2', '1998-09-29', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter.'),
    (12, 10, 'O Futuro de Ciel e Sebastian Parte 2', '2007-02-21', 'Ciel e Sebastian discutem seus planos futuros novamente.'),
    (13, 10, 'A Vida com as Deusas na Terra Parte 3', '1989-01-11', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 10, 'A Captura da Nona Carta', '1996-08-21', 'Sakura captura sua nona carta mágica.'),
    (15, 10, 'O Treinamento Avançado de Ranma e Akane Parte 2', '1987-11-27', 'Ranma e Akane continuam avançando em seu treinamento conjunto.'),
    (1, 11, 'A Luta contra Lucci Parte 2', '1997-12-16', 'Luffy continua sua luta contra Rob Lucci para salvar Robin.'),
    (2, 11, 'A Promessa de Kankuro', '2000-03-07', 'Naruto faz uma promessa importante para Kankuro.'),
    (3, 11, 'A Celebração na Muralha Parte 2', '2010-02-03', 'A humanidade continua celebrando a paz restaurada na muralha.'),
    (4, 11, 'O Treinamento com Sakonji Urokodaki Parte 2', '2016-07-05', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
    (5, 11, 'A Batalha contra Ishida Parte 2', '2001-12-25', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
    (6, 11, 'O Encontro com Shizuku', '1998-09-29', 'Killua conhece Shizuku Murasaki, um membro dos Homens de Preto.'),
    (7, 11, 'A Fuga de Anteiku Parte 3', '2012-01-26', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
    (8, 11, 'A Conclusão da Guerra dos Shinigamis Parte 2', '2004-05-20', 'Light enfrenta a conclusão da guerra entre os shinigamis novamente.'),
    (9, 11, 'A Expansão do Reino de Falconia Parte 2', '1990-01-12', 'Griffith continua expandindo seu poder no Reino de Falconia.'),
    (10, 11, 'A Batalha contra Nephrite e Zoisite Parte 2', '1991-08-15', 'Sailor Moon enfrenta os generais Nephrite e Zoisite novamente.'),
    (11, 11, 'O Desafio Final de Gon e Killua Parte 3', '1998-10-13', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter novamente.'),
    (12, 11, 'O Futuro Incerto de Ciel e Sebastian Parte 2', '2007-03-07', 'Ciel e Sebastian discutem seu futuro incerto novamente.'),
    (13, 11, 'A Vida com as Deusas na Terra Parte 4', '1989-01-25', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 11, 'A Captura da Décima Carta', '1996-09-04', 'Sakura captura sua décima carta mágica.'),
    (15, 11, 'O Treinamento Final de Ranma e Akane Parte 2', '1987-12-11', 'Ranma e Akane concluem seu treinamento conjunto novamente.'),
    (1, 12, 'A Batalha contra Kaku Parte 2', '1997-12-30', 'Luffy continua sua luta contra Kaku para salvar seus amigos.'),
    (2, 12, 'A Promessa de Temari Parte 2', '2000-03-21', 'Naruto faz uma promessa importante para Temari novamente.'),
    (3, 12, 'A Renovação da Muralha Parte 2', '2010-02-17', 'A muralha é renovada e a paz é mantida na humanidade novamente.'),
    (4, 12, 'O Encontro com Giyu Tomioka Parte 2', '2016-07-19', 'Tanjiro continua conhecendo Giyu Tomioka, um caçador de demônios de elite.'),
    (5, 12, 'A Batalha contra Orihime Parte 2', '2002-01-08', 'Ichigo enfrenta Orihime Inoue novamente em uma luta emocional.'),
    (6, 12, 'O Encontro com Machi', '1998-10-13', 'Killua conhece Machi Komacine, um membro dos Homens de Preto.'),
    (7, 12, 'A Luta contra Jason Parte 2', '2012-02-09', 'Kaneki continua sua luta contra Jason em uma batalha decisiva.'),
    (8, 12, 'O Desfecho da Queda de L Parte 2', '2004-06-03', 'L enfrenta seu desfecho final contra Light novamente.'),
    (9, 12, 'A Estabilização do Reino de Falconia Parte 2', '1990-01-26', 'Griffith estabiliza seu poder no Reino de Falconia novamente.'),
    (10, 12, 'A Batalha contra os Shitennou Parte 3', '1991-08-29', 'Sailor Moon enfrenta os generais Shitennou mais uma vez.'),
    (11, 12, 'O Desafio Final de Gon e Killua Parte 4', '1998-10-27', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
    (12, 12, 'O Futuro de Ciel e Sebastian Parte 3', '2007-03-21', 'Ciel e Sebastian discutem seus planos futuros novamente.'),
    (13, 12, 'A Vida com as Deusas na Terra Parte 5', '1989-02-08', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 12, 'A Captura da Décima Primeira Carta', '1996-09-18', 'Sakura captura sua décima primeira carta mágica.'),
    (15, 12, 'O Treinamento Avançado de Ranma e Akane Parte 3', '1987-12-25', 'Ranma e Akane continuam avançando em seu treinamento conjunto.'),
    (1, 13, 'A Luta contra Enel Parte 2', '1998-01-13', 'Luffy continua sua luta contra o deus Enel para salvar a Ilha Skypiea.'),
    (2, 13, 'A Promessa de Kankuro Parte 2', '2000-04-04', 'Naruto faz uma promessa importante para Kankuro novamente.'),
    (3, 13, 'A Celebração na Muralha Parte 3', '2010-03-03', 'A humanidade continua celebrando a paz restaurada na muralha novamente.'),
    (4, 13, 'O Treinamento com Sakonji Urokodaki Parte 3', '2016-08-02', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
    (5, 13, 'A Batalha contra Ishida Parte 3', '2002-01-22', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
    (6, 13, 'O Encontro com Nobunaga', '1998-10-27', 'Killua conhece Nobunaga Hazama, um membro dos Homens de Preto.'),
    (7, 13, 'A Fuga de Anteiku Parte 4', '2012-02-23', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
    (8, 13, 'A Conclusão da Guerra dos Shinigamis Parte 3', '2004-06-17', 'Light enfrenta a conclusão da guerra entre os shinigamis mais uma vez.'),
    (9, 13, 'A Expansão do Reino de Falconia Parte 3', '1990-02-09', 'Griffith continua expandindo seu poder no Reino de Falconia.'),
    (10, 13, 'A Batalha contra Nephrite e Zoisite Parte 3', '1991-09-12', 'Sailor Moon enfrenta os generais Nephrite e Zoisite mais uma vez.'),
    (11, 13, 'O Desafio Final de Gon e Killua Parte 5', '1998-11-10', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
    (12, 13, 'O Futuro Incerto de Ciel e Sebastian Parte 3', '2007-04-04', 'Ciel e Sebastian discutem seu futuro incerto mais uma vez.'),
    (13, 13, 'A Vida com as Deusas na Terra Parte 6', '1989-02-22', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 13, 'A Captura da Décima Segunda Carta', '1996-10-02', 'Sakura captura sua décima segunda carta mágica.'),
    (15, 13, 'O Treinamento Final de Ranma e Akane Parte 3', '1988-01-08', 'Ranma e Akane concluem seu treinamento conjunto mais uma vez.'),
    (1, 14, 'A Batalha contra Crocodile Parte 2', '1998-01-27', 'Luffy continua sua luta contra Crocodile para salvar Alabasta.'),
    (2, 14, 'A Promessa de Gaara Parte 2', '2000-04-18', 'Naruto faz uma promessa importante para Gaara novamente.'),
    (3, 14, 'A Paz na Muralha Parte 2', '2010-03-17', 'A muralha é restaurada e a paz retorna à humanidade novamente.'),
    (4, 14, 'O Encontro com Inosuke Parte 2', '2016-08-16', 'Tanjiro continua conhecendo Inosuke Hashibira, um caçador de demônios selvagem.'),
    (5, 14, 'A Batalha contra Chad Parte 2', '2002-02-05', 'Ichigo enfrenta Chad Yasutora novamente em uma luta intensa.'),
    (6, 14, 'O Encontro com Kortopi', '1998-11-10', 'Killua conhece Kortopi, um membro dos Homens de Preto.'),
    (7, 14, 'A Luta contra Yamori Parte 2', '2012-03-08', 'Kaneki continua sua luta contra Yamori em uma batalha brutal.'),
    (8, 14, 'O Desfecho da Queda de L Parte 3', '2004-07-01', 'L enfrenta seu desfecho final contra Light mais uma vez.'),
    (9, 14, 'A Consolidação do Reino de Falconia Parte 2', '1990-02-23', 'Griffith consolida seu poder no Reino de Falconia mais uma vez.'),
    (10, 14, 'A Batalha contra os Shitennou Parte 4', '1991-09-26', 'Sailor Moon enfrenta os generais Shitennou mais uma vez.'),
    (11, 14, 'O Desafio Final de Gon e Killua Parte 6', '1998-11-24', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
    (12, 14, 'O Futuro de Ciel e Sebastian Parte 4', '2007-04-18', 'Ciel e Sebastian discutem seus planos futuros mais uma vez.'),
    (13, 14, 'A Vida com as Deusas na Terra Parte 7', '1989-03-08', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 14, 'A Captura da Décima Terceira Carta', '1996-10-16', 'Sakura captura sua décima terceira carta mágica.'),
    (15, 14, 'O Treinamento Avançado de Ranma e Akane Parte 4', '1988-01-22', 'Ranma e Akane continuam avançando em seu treinamento conjunto.'),
    (1, 15, 'A Luta contra Lucci Parte 3', '1998-02-10', 'Luffy continua sua luta contra Rob Lucci para salvar Robin.'),
    (2, 15, 'A Promessa de Kankuro Parte 3', '2000-05-02', 'Naruto faz uma promessa importante para Kankuro novamente.'),
    (3, 15, 'A Celebração na Muralha Parte 4', '2010-03-31', 'A humanidade continua celebrando a paz restaurada na muralha novamente.'),
    (4, 15, 'O Treinamento com Sakonji Urokodaki Parte 4', '2016-08-30', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
    (5, 15, 'A Batalha contra Ishida Parte 4', '2002-02-19', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
    (6, 15, 'O Encontro com Feitan', '1998-11-24', 'Killua conhece Feitan Portor, um membro dos Homens de Preto.'),
    (7, 15, 'A Fuga de Anteiku Parte 5', '2012-03-22', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
    (8, 15, 'A Conclusão da Guerra dos Shinigamis Parte 4', '2004-07-15', 'Light enfrenta a conclusão da guerra entre os shinigamis mais uma vez.'),
    (9, 15, 'A Expansão do Reino de Falconia Parte 4', '1990-03-09', 'Griffith continua expandindo seu poder no Reino de Falconia.'),
    (10, 15, 'A Batalha contra Nephrite e Zoisite Parte 4', '1991-10-10', 'Sailor Moon enfrenta os generais Nephrite e Zoisite mais uma vez.'),
    (11, 15, 'O Desafio Final de Gon e Killua Parte 7', '1998-12-08', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
    (12, 15, 'O Futuro Incerto de Ciel e Sebastian Parte 4', '2007-05-02', 'Ciel e Sebastian discutem seu futuro incerto mais uma vez.'),
    (13, 15, 'A Vida com as Deusas na Terra Parte 8', '1989-03-22', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 15, 'A Captura da Décima Quarta Carta', '1996-10-30', 'Sakura captura sua décima quarta carta mágica.'),
    (15, 15, 'O Treinamento Final de Ranma e Akane Parte 4', '1988-02-05', 'Ranma e Akane concluem seu treinamento conjunto mais uma vez.'),
    (1, 16, 'A Batalha contra Kaku Parte 3', '1998-02-24', 'Luffy continua sua luta contra Kaku para salvar seus amigos.'),
    (2, 16, 'A Promessa de Temari Parte 3', '2000-05-16', 'Naruto faz uma promessa importante para Temari novamente.'),
    (3, 16, 'A Renovação da Muralha Parte 3', '2010-04-14', 'A muralha é renovada e a paz é mantida na humanidade novamente.'),
    (4, 16, 'O Encontro com Giyu Tomioka Parte 3', '2016-09-13', 'Tanjiro continua conhecendo Giyu Tomioka, um caçador de demônios de elite.'),
    (5, 16, 'A Batalha contra Orihime Parte 3', '2002-03-05', 'Ichigo enfrenta Orihime Inoue novamente em uma luta emocional.'),
    (6, 16, 'O Encontro com Pakunoda', '1998-12-08', 'Killua conhece Pakunoda, um membro dos Homens de Preto.'),
    (7, 16, 'A Luta contra Yamori Parte 3', '2012-04-05', 'Kaneki continua sua luta contra Yamori em uma batalha brutal.'),
    (8, 16, 'O Desfecho da Queda de L Parte 4', '2004-07-29', 'L enfrenta seu desfecho final contra Light mais uma vez.'),
    (9, 16, 'A Consolidação do Reino de Falconia Parte 3', '1990-03-23', 'Griffith consolida seu poder no Reino de Falconia mais uma vez.'),
    (10, 16, 'A Batalha contra os Shitennou Parte 5', '1991-11-07', 'Sailor Moon enfrenta os generais Shitennou mais uma vez.'),
    (11, 16, 'O Desafio Final de Gon e Killua Parte 8', '1998-12-22', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
    (12, 16, 'O Futuro de Ciel e Sebastian Parte 5', '2007-05-16', 'Ciel e Sebastian discutem seus planos futuros mais uma vez.'),
    (13, 16, 'A Vida com as Deusas na Terra Parte 9', '1989-04-05', 'Keiichi continua explorando a vida com as deusas na Terra.'),
    (14, 16, 'A Captura da Décima Quinta Carta', '1996-11-13', 'Sakura captura sua décima quinta carta mágica.'),
    (15, 16, 'O Treinamento Avançado de Ranma e Akane Parte 5', '1988-02-19', 'Ranma e Akane continuam avançando em seu treinamento conjunto.');",



];
?>